#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mknod -m 666 /dev/ttyS0 c 4 64

echo -e "\nBem-vindo ao IDP Linux!\n\n"
echo -e "Boot levou $(cut -d' ' -f1 /proc/uptime) segundos!\n\n"
setsid cttyhack sh

poweroff -f
exec /bin/sh
